# kustomize.yaml

# kustomize file for this overlay

# --------------------------------------------------------------------------- #

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# define the location of bases
bases:
  - "../../bases"

# apply labels to every resource
commonLabels:
  app: "demo"
  env: "scenario-4"

# define image for this overlay
images:
  - name: "k8s-demo"
    newTag: "foo"

# define any metadata for this overlay
metadata:
  name: "demo"

# define the namespace for this overlay
namespace: "scenario-4"

#EOF