# kustomize.yaml

# kustomize file for this overlay

# --------------------------------------------------------------------------- #

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# define the location of bases
bases:
  - "../../bases"

# apply labels to every resource
commonLabels:
  app: "demo"
  env: "scenario-2"

# create a different configmap with wrong value to cause error
configMapGenerator:
- name: "common2"
  literals:
    - "DEMO_YEAR=2021"

# define image for this overlay
images:
  - name: "k8s-demo"
    newTag: "v0"

# define any metadata for this overlay
metadata:
  name: "demo"

# define the namespace for this overlay
namespace: "scenario-2"

# apply specific patches for the specific scenario
patchesJson6902:
  - target:
      group: "apps"
      version: "v1"
      kind: "Deployment"
      name: "demo"
    path: "envFrom.yaml"
#EOF